export enum VisitorEnum {
    NaamBezoekers= "NaamBezoekers",
    LogoThuisploeg = "LogoThuisploeg",
    NaamThuisploeg = "NaamThuisploeg",
    NavoegselBezoekers = "NavoegselBezoekers",
    NavoegselThuisploeg = "NavoegselThuisploeg",
    RoepNaamSpeler = "RoepNaamSpeler",
    Rugnummer = "Rugnummer",
    RugnummerNaam = "RugnummerNaam",
    RugnummerNaamVoornaam = "RugnummerNaamVoornaam",
    Score = "Score",
    Speeldag = "Speeldag",
    SpelerEnoFVrijeTekst = "SpelerEnoFVrijeTekst",
    SponsorLogo = "SponsorLogo",
    SponsorNaam = "SponsorNaam",
    Stadion = "Stadion",
    SubTemplate = "SubTemplate",
    Tekst = "Tekst",
    VasteAfbeelding = "VasteAfbeelding",
    Video = "Video",
    Voornaam = "Voornaam",
    VoorNaamEnFamilienaam = "VoorNaamEnFamilienaam",
    VoorVoegselBezoekers = "VoorVoegselBezoekers",
    VoorVoegselThuisploeg="VoorVoegselThuisploeg",
    WedstrijdTypeLogo = "WedstrijdTypeLogo",
    WedstrijdTypeNaam= "WedstrijdTypeNaam",
}

export const FileType2LabelMapping: Record<VisitorEnum, string> = {
    [VisitorEnum.NaamBezoekers]: "NaamBezoekers",
    [VisitorEnum.LogoThuisploeg]: "LogoThuisploeg",
    [VisitorEnum.NaamThuisploeg]: "NaamThuisploeg",
    [VisitorEnum.NavoegselBezoekers]: "NavoegselBezoekers",
    [VisitorEnum.NavoegselThuisploeg]: "NavoegselThuisploeg",
    [VisitorEnum.RoepNaamSpeler]: "RoepNaamSpeler",
    [VisitorEnum.Rugnummer]: "Rugnummer",
    [VisitorEnum.RugnummerNaam]: "RugnummerNaam",
    [VisitorEnum.RugnummerNaamVoornaam]: "RugnummerNaamVoornaam",
    [VisitorEnum.Score]: "Score",
    [VisitorEnum.Speeldag]: "Speeldag",
    [VisitorEnum.SpelerEnoFVrijeTekst]: "SpelerEnoFVrijeTekst",
    [VisitorEnum.SponsorLogo]: "SponsorLogo",
    [VisitorEnum.SponsorNaam]: "SponsorNaam",
    [VisitorEnum.Stadion]: "Stadion",
    [VisitorEnum.SubTemplate]: "SubTemplate",
    [VisitorEnum.Tekst]: "Tekst",
    [VisitorEnum.VasteAfbeelding]: "VasteAfbeelding",
    [VisitorEnum.Video]: "Video",
    [VisitorEnum.Voornaam]: "Voornaam",
    [VisitorEnum.VoorNaamEnFamilienaam]: "VoorNaamEnFamilienaam",
    [VisitorEnum.VoorVoegselBezoekers]: "VoorVoegselBezoekers",
    [VisitorEnum.VoorVoegselThuisploeg]: "VoorVoegselThuisploeg",
    [VisitorEnum.WedstrijdTypeLogo]: "WedstrijdTypeLogo",
    [VisitorEnum.WedstrijdTypeNaam]: "WedstrijdTypeNaam",
};
